"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "./components/shared/sidebar"
import Navbar from "./components/shared/navbar";
import React, {use, useState} from "react";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const [isSidebarCollapsed, setIsSidebarCollapsed] = useState(false);

  return (
    <html lang="en" className="h-screen">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-50 h-screen`}>
        <div className="flex h-screen">
          <Sidebar 
          isCollapsed={isSidebarCollapsed}
        onToggle={() => setIsSidebarCollapsed((prev) => !prev)}/>
          <Navbar isSidebarCollapsed={isSidebarCollapsed} />
          <main className="flex-1 overflow-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
